export const LANDING_PAGE_LATEST_EVENT_REQUEST =
  "LANDING_PAGE_LATEST_EVENT_REQUEST";
export const LANDING_PAGE_LATEST_EVENT_SUCCESS =
  "LANDING_PAGE_LATEST_EVENT_SUCCESS";
export const LANDING_PAGE_LATEST_EVENT_FAIL = "LANDING_PAGE_LATEST_EVENT_FAIL";

export const TESTIMONIAL_REQUEST = "TESTIMONIAL_REQUEST";
export const TESTIMONIAL_SUCCESS = "TESTIMONIAL_SUCCESS";
export const TESTIMONIAL_FAIL = "TESTIMONIAL_FAIL";

export const LANDING_PAGE_ALL_SCHOOL_REQUEST = "LANDING_PAGE_SCHOOL_REQUEST";
export const LANDING_PAGE_ALL_SCHOOL_SUCCESS = "LANDING_PAGE_SCHOOL_SUCCESS";
export const LANDING_PAGE_ALL_SCHOOL_FAIL = "LANDING_PAGE_SCHOOL_SUCCESS";
