export const SCHOOL_LIST_REQUEST = "SCHOOL_LIST_REQUEST";
export const SCHOOL_LIST_SUCCESS = "SCHOOL_LIST_SUCCESS";
export const SCHOOL_LIST_FAIL = "SCHOOL_LIST_FAIL";

export const SCHOOL_DETAIL_REQUEST = "SCHOOL_DETAIL_REQUEST";
export const SCHOOL_DETAIL_SUCCESS = "SCHOOL_DETAIL_SUCCESS";
export const SCHOOL_DETAIL_FAIL = "SCHOOL_DETAIL_FAIL";
